// Parottasalna DSA sheet — edit freely.
// Each question is "Title | leetcode-slug | E/M/H | pattern-id, pattern-id".
// The first pattern is the main one. The slug doubles as the question's id for saved
// progress, so changing a slug resets that question's progress.
window.DSA_SHEET = {
  name: "Parottasalna DSA Sheet",
  patterns: [
    { id: "hashing", name: "Hashing", desc: "Use a hash map or set for O(1) lookups — counting, de-duplicating and remembering what you've seen." },
    { id: "two-pointers", name: "Two Pointers", desc: "Walk two indexes towards each other or in the same direction over a sorted array, string or list." },
    { id: "sliding-window", name: "Sliding Window", desc: "Grow and shrink a window over an array or string to track the best contiguous range." },
    { id: "prefix-sum", name: "Prefix Sum", desc: "Precompute running totals so any range sum or product is a quick subtraction." },
    { id: "kadane", name: "Kadane's Algorithm", desc: "Track the best answer ending at each index to find the best contiguous subarray in one pass." },
    { id: "sorting", name: "Sorting", desc: "Sort first so that order makes the rest of the problem simple." },
    { id: "intervals", name: "Intervals", desc: "Sort intervals by start and merge, insert or count overlaps." },
    { id: "binary-search", name: "Binary Search", desc: "Halve the search space each step — on a sorted array, a rotated array or the answer itself." },
    { id: "cyclic-sort", name: "Cyclic Sort", desc: "Numbers in a known range go to their own index, revealing what's missing or duplicated." },
    { id: "fast-slow", name: "Fast & Slow Pointers", desc: "Move one pointer twice as fast to find cycles, middles and meeting points." },
    { id: "ll-reversal", name: "In-place Linked List Reversal", desc: "Reverse all or part of a linked list by re-pointing next pointers." },
    { id: "linked-list", name: "Linked List Manipulation", desc: "Dummy nodes and careful pointer updates to insert, delete and rearrange nodes." },
    { id: "stack", name: "Stack", desc: "Last-in, first-out: matching brackets, evaluating expressions and undoing steps." },
    { id: "monotonic-stack", name: "Monotonic Stack / Queue", desc: "Keep a stack or deque in sorted order to find the next greater or smaller element fast." },
    { id: "heap", name: "Heap / Top K", desc: "Use a priority queue to always pull the smallest or largest item — the top K, the Kth, the next best." },
    { id: "two-heaps", name: "Two Heaps", desc: "A max-heap and a min-heap split the data in half to track the median." },
    { id: "k-way-merge", name: "K-way Merge", desc: "Merge several sorted lists by always taking the smallest head from a heap." },
    { id: "tree-dfs", name: "Tree DFS", desc: "Recursion down a tree (pre, in or post order) — depths, paths and subtree answers." },
    { id: "tree-bfs", name: "Tree BFS", desc: "Visit a tree level by level with a queue." },
    { id: "graph-traversal", name: "Graph DFS / BFS", desc: "Explore grids and graphs, mark visited nodes, and count or copy components." },
    { id: "topo-sort", name: "Topological Sort", desc: "Order tasks with dependencies and detect cycles in directed graphs." },
    { id: "union-find", name: "Union Find", desc: "Merge sets and check connectivity almost instantly with a disjoint-set structure." },
    { id: "shortest-path", name: "Shortest Path & MST", desc: "Dijkstra, BFS on unweighted graphs, Bellman-Ford-style limits and minimum spanning trees." },
    { id: "backtracking", name: "Backtracking", desc: "Build candidates step by step and undo choices to explore every valid combination." },
    { id: "trie", name: "Trie", desc: "A prefix tree for fast word and prefix lookups." },
    { id: "greedy", name: "Greedy", desc: "Make the locally best choice at each step when it provably leads to the best overall answer." },
    { id: "dp-1d", name: "1D Dynamic Programming", desc: "An answer for each index built from earlier answers." },
    { id: "knapsack", name: "Knapsack DP", desc: "Pick items to hit a target sum or capacity — 0/1 and unbounded." },
    { id: "dp-grid", name: "Grid DP", desc: "Each cell's answer comes from its neighbours — paths and squares in a grid." },
    { id: "dp-strings", name: "DP on Strings", desc: "Compare two strings with a 2D table — subsequences, edits and matching." },
    { id: "dp-interval", name: "Interval DP", desc: "Solve every sub-range i..j, from short ranges to long ones." },
    { id: "bit-manipulation", name: "Bit Manipulation", desc: "XOR, masks and shifts to solve problems in constant space." },
    { id: "math", name: "Math", desc: "Number properties, digits, modular tricks and fast exponentiation." },
    { id: "matrix", name: "Matrix Simulation", desc: "Walk, rotate and update 2D grids in place." },
    { id: "string", name: "String Manipulation", desc: "Parse, build and transform strings carefully, character by character." },
    { id: "design", name: "Design", desc: "Build a data structure with the required operations and time limits." },
  ],
  topics: [
    { id: "arrays", name: "Arrays", questions: [
      "Two Sum | two-sum | E | hashing",
      "Best Time to Buy and Sell Stock | best-time-to-buy-and-sell-stock | E | kadane, greedy",
      "Contains Duplicate | contains-duplicate | E | hashing",
      "Majority Element | majority-element | E | hashing",
      "Move Zeroes | move-zeroes | E | two-pointers",
      "Merge Sorted Array | merge-sorted-array | E | two-pointers",
      "Maximum Subarray | maximum-subarray | M | kadane",
      "Product of Array Except Self | product-of-array-except-self | M | prefix-sum",
      "Maximum Product Subarray | maximum-product-subarray | M | kadane",
      "3Sum | 3sum | M | two-pointers, sorting",
      "Container With Most Water | container-with-most-water | M | two-pointers",
      "Sort Colors | sort-colors | M | two-pointers",
      "Next Permutation | next-permutation | M | two-pointers",
      "Rotate Array | rotate-array | M | two-pointers",
      "Subarray Sum Equals K | subarray-sum-equals-k | M | prefix-sum, hashing",
      "Longest Consecutive Sequence | longest-consecutive-sequence | M | hashing",
      "Find the Duplicate Number | find-the-duplicate-number | M | fast-slow, cyclic-sort",
      "Merge Intervals | merge-intervals | M | intervals, sorting",
      "Insert Interval | insert-interval | M | intervals",
      "Non-overlapping Intervals | non-overlapping-intervals | M | intervals, greedy",
      "First Missing Positive | first-missing-positive | H | cyclic-sort",
      "Trapping Rain Water | trapping-rain-water | H | two-pointers, monotonic-stack",
    ] },
    { id: "matrix", name: "Matrix", questions: [
      "Set Matrix Zeroes | set-matrix-zeroes | M | matrix",
      "Spiral Matrix | spiral-matrix | M | matrix",
      "Rotate Image | rotate-image | M | matrix",
      "Search a 2D Matrix | search-a-2d-matrix | M | binary-search",
      "Search a 2D Matrix II | search-a-2d-matrix-ii | M | matrix, two-pointers",
      "Valid Sudoku | valid-sudoku | M | hashing, matrix",
      "Game of Life | game-of-life | M | matrix",
      "Word Search | word-search | M | backtracking",
    ] },
    { id: "strings", name: "Strings", questions: [
      "Valid Anagram | valid-anagram | E | hashing",
      "Valid Palindrome | valid-palindrome | E | two-pointers",
      "Valid Parentheses | valid-parentheses | E | stack",
      "Longest Common Prefix | longest-common-prefix | E | string",
      "Roman to Integer | roman-to-integer | E | string",
      "Find the Index of the First Occurrence in a String | find-the-index-of-the-first-occurrence-in-a-string | E | string, two-pointers",
      "Longest Substring Without Repeating Characters | longest-substring-without-repeating-characters | M | sliding-window, hashing",
      "Longest Repeating Character Replacement | longest-repeating-character-replacement | M | sliding-window",
      "Group Anagrams | group-anagrams | M | hashing",
      "Longest Palindromic Substring | longest-palindromic-substring | M | two-pointers, dp-strings",
      "Palindromic Substrings | palindromic-substrings | M | two-pointers, dp-interval",
      "Reverse Words in a String | reverse-words-in-a-string | M | string, two-pointers",
      "String to Integer (atoi) | string-to-integer-atoi | M | string",
      "Permutation in String | permutation-in-string | M | sliding-window",
      "Find All Anagrams in a String | find-all-anagrams-in-a-string | M | sliding-window, hashing",
      "Zigzag Conversion | zigzag-conversion | M | string",
      "Integer to Roman | integer-to-roman | M | greedy, string",
      "Minimum Window Substring | minimum-window-substring | H | sliding-window, hashing",
    ] },
    { id: "two-pointers", name: "Two Pointers & Sliding Window", questions: [
      "Remove Duplicates from Sorted Array | remove-duplicates-from-sorted-array | E | two-pointers",
      "Two Sum II - Input Array Is Sorted | two-sum-ii-input-array-is-sorted | M | two-pointers",
      "4Sum | 4sum | M | two-pointers, sorting",
      "Boats to Save People | boats-to-save-people | M | two-pointers, greedy",
      "Minimum Size Subarray Sum | minimum-size-subarray-sum | M | sliding-window",
      "Max Consecutive Ones III | max-consecutive-ones-iii | M | sliding-window",
      "Fruit Into Baskets | fruit-into-baskets | M | sliding-window, hashing",
      "Sliding Window Maximum | sliding-window-maximum | H | sliding-window, monotonic-stack",
    ] },
    { id: "searching-sorting", name: "Searching & Sorting", questions: [
      "Binary Search | binary-search | E | binary-search",
      "Search Insert Position | search-insert-position | E | binary-search",
      "Sqrt(x) | sqrtx | E | binary-search",
      "Search in Rotated Sorted Array | search-in-rotated-sorted-array | M | binary-search",
      "Find Minimum in Rotated Sorted Array | find-minimum-in-rotated-sorted-array | M | binary-search",
      "Find First and Last Position of Element in Sorted Array | find-first-and-last-position-of-element-in-sorted-array | M | binary-search",
      "Find Peak Element | find-peak-element | M | binary-search",
      "Koko Eating Bananas | koko-eating-bananas | M | binary-search",
      "Capacity To Ship Packages Within D Days | capacity-to-ship-packages-within-d-days | M | binary-search",
      "Time Based Key-Value Store | time-based-key-value-store | M | binary-search, design",
      "Sort an Array | sort-an-array | M | sorting",
      "Split Array Largest Sum | split-array-largest-sum | H | binary-search",
      "Median of Two Sorted Arrays | median-of-two-sorted-arrays | H | binary-search",
    ] },
    { id: "linked-list", name: "Linked List", questions: [
      "Reverse Linked List | reverse-linked-list | E | ll-reversal",
      "Merge Two Sorted Lists | merge-two-sorted-lists | E | two-pointers, linked-list",
      "Linked List Cycle | linked-list-cycle | E | fast-slow",
      "Middle of the Linked List | middle-of-the-linked-list | E | fast-slow",
      "Intersection of Two Linked Lists | intersection-of-two-linked-lists | E | two-pointers",
      "Palindrome Linked List | palindrome-linked-list | E | fast-slow, ll-reversal",
      "Remove Linked List Elements | remove-linked-list-elements | E | linked-list",
      "Linked List Cycle II | linked-list-cycle-ii | M | fast-slow",
      "Remove Nth Node From End of List | remove-nth-node-from-end-of-list | M | two-pointers, linked-list",
      "Reorder List | reorder-list | M | fast-slow, ll-reversal",
      "Add Two Numbers | add-two-numbers | M | linked-list, math",
      "Odd Even Linked List | odd-even-linked-list | M | linked-list",
      "Rotate List | rotate-list | M | linked-list",
      "Sort List | sort-list | M | sorting, fast-slow",
      "Copy List with Random Pointer | copy-list-with-random-pointer | M | hashing, linked-list",
      "LRU Cache | lru-cache | M | design, hashing",
      "Merge k Sorted Lists | merge-k-sorted-lists | H | k-way-merge, heap",
      "Reverse Nodes in k-Group | reverse-nodes-in-k-group | H | ll-reversal",
    ] },
    { id: "stacks-queues", name: "Stacks & Queues", questions: [
      "Implement Queue using Stacks | implement-queue-using-stacks | E | design, stack",
      "Implement Stack using Queues | implement-stack-using-queues | E | design, stack",
      "Next Greater Element I | next-greater-element-i | E | monotonic-stack, hashing",
      "Min Stack | min-stack | M | design, stack",
      "Evaluate Reverse Polish Notation | evaluate-reverse-polish-notation | M | stack",
      "Daily Temperatures | daily-temperatures | M | monotonic-stack",
      "Next Greater Element II | next-greater-element-ii | M | monotonic-stack",
      "Online Stock Span | online-stock-span | M | monotonic-stack, design",
      "Asteroid Collision | asteroid-collision | M | stack",
      "Decode String | decode-string | M | stack",
      "Simplify Path | simplify-path | M | stack, string",
      "Remove K Digits | remove-k-digits | M | monotonic-stack, greedy",
      "Car Fleet | car-fleet | M | stack, sorting",
      "Largest Rectangle in Histogram | largest-rectangle-in-histogram | H | monotonic-stack",
      "Basic Calculator | basic-calculator | H | stack",
    ] },
    { id: "binary-trees", name: "Binary Trees", questions: [
      "Binary Tree Inorder Traversal | binary-tree-inorder-traversal | E | tree-dfs, stack",
      "Binary Tree Preorder Traversal | binary-tree-preorder-traversal | E | tree-dfs, stack",
      "Binary Tree Postorder Traversal | binary-tree-postorder-traversal | E | tree-dfs, stack",
      "Maximum Depth of Binary Tree | maximum-depth-of-binary-tree | E | tree-dfs",
      "Invert Binary Tree | invert-binary-tree | E | tree-dfs",
      "Same Tree | same-tree | E | tree-dfs",
      "Symmetric Tree | symmetric-tree | E | tree-dfs",
      "Diameter of Binary Tree | diameter-of-binary-tree | E | tree-dfs",
      "Balanced Binary Tree | balanced-binary-tree | E | tree-dfs",
      "Subtree of Another Tree | subtree-of-another-tree | E | tree-dfs",
      "Path Sum | path-sum | E | tree-dfs",
      "Binary Tree Level Order Traversal | binary-tree-level-order-traversal | M | tree-bfs",
      "Binary Tree Zigzag Level Order Traversal | binary-tree-zigzag-level-order-traversal | M | tree-bfs",
      "Binary Tree Right Side View | binary-tree-right-side-view | M | tree-bfs",
      "Maximum Width of Binary Tree | maximum-width-of-binary-tree | M | tree-bfs",
      "Path Sum II | path-sum-ii | M | tree-dfs, backtracking",
      "Count Good Nodes in Binary Tree | count-good-nodes-in-binary-tree | M | tree-dfs",
      "Lowest Common Ancestor of a Binary Tree | lowest-common-ancestor-of-a-binary-tree | M | tree-dfs",
      "Construct Binary Tree from Preorder and Inorder Traversal | construct-binary-tree-from-preorder-and-inorder-traversal | M | tree-dfs, hashing",
      "Flatten Binary Tree to Linked List | flatten-binary-tree-to-linked-list | M | tree-dfs",
      "All Nodes Distance K in Binary Tree | all-nodes-distance-k-in-binary-tree | M | tree-bfs, graph-traversal",
      "Vertical Order Traversal of a Binary Tree | vertical-order-traversal-of-a-binary-tree | H | tree-bfs, sorting",
      "Binary Tree Maximum Path Sum | binary-tree-maximum-path-sum | H | tree-dfs",
      "Serialize and Deserialize Binary Tree | serialize-and-deserialize-binary-tree | H | tree-dfs, design",
    ] },
    { id: "bst", name: "Binary Search Trees", questions: [
      "Search in a Binary Search Tree | search-in-a-binary-search-tree | E | tree-dfs",
      "Convert Sorted Array to Binary Search Tree | convert-sorted-array-to-binary-search-tree | E | tree-dfs",
      "Two Sum IV - Input is a BST | two-sum-iv-input-is-a-bst | E | tree-dfs, hashing",
      "Insert into a Binary Search Tree | insert-into-a-binary-search-tree | M | tree-dfs",
      "Delete Node in a BST | delete-node-in-a-bst | M | tree-dfs",
      "Validate Binary Search Tree | validate-binary-search-tree | M | tree-dfs",
      "Kth Smallest Element in a BST | kth-smallest-element-in-a-bst | M | tree-dfs",
      "Lowest Common Ancestor of a Binary Search Tree | lowest-common-ancestor-of-a-binary-search-tree | M | tree-dfs",
      "Binary Search Tree Iterator | binary-search-tree-iterator | M | design, stack",
      "Construct Binary Search Tree from Preorder Traversal | construct-binary-search-tree-from-preorder-traversal | M | tree-dfs",
      "Trim a Binary Search Tree | trim-a-binary-search-tree | M | tree-dfs",
      "Recover Binary Search Tree | recover-binary-search-tree | M | tree-dfs",
    ] },
    { id: "heap", name: "Heap / Priority Queue", questions: [
      "Kth Largest Element in a Stream | kth-largest-element-in-a-stream | E | heap, design",
      "Last Stone Weight | last-stone-weight | E | heap",
      "Kth Largest Element in an Array | kth-largest-element-in-an-array | M | heap",
      "Top K Frequent Elements | top-k-frequent-elements | M | heap, hashing",
      "K Closest Points to Origin | k-closest-points-to-origin | M | heap",
      "Sort Characters By Frequency | sort-characters-by-frequency | M | heap, hashing",
      "Task Scheduler | task-scheduler | M | greedy, heap",
      "Reorganize String | reorganize-string | M | greedy, heap",
      "Ugly Number II | ugly-number-ii | M | heap, dp-1d",
      "Design Twitter | design-twitter | M | design, k-way-merge",
      "Find Median from Data Stream | find-median-from-data-stream | H | two-heaps, design",
      "Smallest Range Covering Elements from K Lists | smallest-range-covering-elements-from-k-lists | H | k-way-merge, sliding-window",
    ] },
    { id: "greedy", name: "Greedy", questions: [
      "Assign Cookies | assign-cookies | E | greedy, sorting",
      "Lemonade Change | lemonade-change | E | greedy",
      "Best Time to Buy and Sell Stock II | best-time-to-buy-and-sell-stock-ii | M | greedy",
      "Jump Game | jump-game | M | greedy",
      "Jump Game II | jump-game-ii | M | greedy",
      "Gas Station | gas-station | M | greedy",
      "Hand of Straights | hand-of-straights | M | greedy, hashing",
      "Partition Labels | partition-labels | M | greedy, two-pointers",
      "Valid Parenthesis String | valid-parenthesis-string | M | greedy",
      "Minimum Number of Arrows to Burst Balloons | minimum-number-of-arrows-to-burst-balloons | M | intervals, greedy",
      "Merge Triplets to Form Target Triplet | merge-triplets-to-form-target-triplet | M | greedy",
      "Candy | candy | H | greedy",
    ] },
    { id: "backtracking", name: "Backtracking", questions: [
      "Subsets | subsets | M | backtracking",
      "Subsets II | subsets-ii | M | backtracking",
      "Permutations | permutations | M | backtracking",
      "Permutations II | permutations-ii | M | backtracking",
      "Combinations | combinations | M | backtracking",
      "Combination Sum | combination-sum | M | backtracking",
      "Combination Sum II | combination-sum-ii | M | backtracking",
      "Generate Parentheses | generate-parentheses | M | backtracking",
      "Letter Combinations of a Phone Number | letter-combinations-of-a-phone-number | M | backtracking",
      "Palindrome Partitioning | palindrome-partitioning | M | backtracking",
      "N-Queens | n-queens | H | backtracking",
      "Sudoku Solver | sudoku-solver | H | backtracking",
    ] },
    { id: "graphs", name: "Graphs", questions: [
      "Flood Fill | flood-fill | E | graph-traversal",
      "Number of Islands | number-of-islands | M | graph-traversal",
      "Max Area of Island | max-area-of-island | M | graph-traversal",
      "Clone Graph | clone-graph | M | graph-traversal, hashing",
      "Rotting Oranges | rotting-oranges | M | graph-traversal",
      "01 Matrix | 01-matrix | M | graph-traversal",
      "Surrounded Regions | surrounded-regions | M | graph-traversal",
      "Pacific Atlantic Water Flow | pacific-atlantic-water-flow | M | graph-traversal",
      "Number of Provinces | number-of-provinces | M | graph-traversal, union-find",
      "Is Graph Bipartite? | is-graph-bipartite | M | graph-traversal",
      "Course Schedule | course-schedule | M | topo-sort",
      "Course Schedule II | course-schedule-ii | M | topo-sort",
      "Find Eventual Safe States | find-eventual-safe-states | M | topo-sort",
      "Redundant Connection | redundant-connection | M | union-find",
      "Accounts Merge | accounts-merge | M | union-find, graph-traversal",
      "Evaluate Division | evaluate-division | M | graph-traversal",
      "Shortest Path in Binary Matrix | shortest-path-in-binary-matrix | M | shortest-path, graph-traversal",
      "Network Delay Time | network-delay-time | M | shortest-path",
      "Cheapest Flights Within K Stops | cheapest-flights-within-k-stops | M | shortest-path",
      "Path With Minimum Effort | path-with-minimum-effort | M | shortest-path",
      "Min Cost to Connect All Points | min-cost-to-connect-all-points | M | shortest-path, union-find",
      "Word Ladder | word-ladder | H | shortest-path, graph-traversal",
      "Swim in Rising Water | swim-in-rising-water | H | shortest-path",
      "Critical Connections in a Network | critical-connections-in-a-network | H | graph-traversal",
    ] },
    { id: "trie", name: "Trie", questions: [
      "Implement Trie (Prefix Tree) | implement-trie-prefix-tree | M | trie, design",
      "Design Add and Search Words Data Structure | design-add-and-search-words-data-structure | M | trie, design",
      "Replace Words | replace-words | M | trie",
      "Longest Word in Dictionary | longest-word-in-dictionary | M | trie",
      "Maximum XOR of Two Numbers in an Array | maximum-xor-of-two-numbers-in-an-array | M | trie, bit-manipulation",
      "Word Search II | word-search-ii | H | trie, backtracking",
    ] },
    { id: "dynamic-programming", name: "Dynamic Programming", questions: [
      "Climbing Stairs | climbing-stairs | E | dp-1d",
      "Fibonacci Number | fibonacci-number | E | dp-1d",
      "Min Cost Climbing Stairs | min-cost-climbing-stairs | E | dp-1d",
      "House Robber | house-robber | M | dp-1d",
      "House Robber II | house-robber-ii | M | dp-1d",
      "Coin Change | coin-change | M | knapsack",
      "Coin Change II | coin-change-ii | M | knapsack",
      "Perfect Squares | perfect-squares | M | knapsack",
      "Combination Sum IV | combination-sum-iv | M | dp-1d",
      "Word Break | word-break | M | dp-1d, hashing",
      "Decode Ways | decode-ways | M | dp-1d",
      "Unique Paths | unique-paths | M | dp-grid",
      "Unique Paths II | unique-paths-ii | M | dp-grid",
      "Minimum Path Sum | minimum-path-sum | M | dp-grid",
      "Triangle | triangle | M | dp-grid",
      "Maximal Square | maximal-square | M | dp-grid",
      "Partition Equal Subset Sum | partition-equal-subset-sum | M | knapsack",
      "Target Sum | target-sum | M | knapsack",
      "Longest Increasing Subsequence | longest-increasing-subsequence | M | dp-1d, binary-search",
      "Longest Common Subsequence | longest-common-subsequence | M | dp-strings",
      "Longest Palindromic Subsequence | longest-palindromic-subsequence | M | dp-strings, dp-interval",
      "Edit Distance | edit-distance | M | dp-strings",
      "Interleaving String | interleaving-string | M | dp-strings",
      "Best Time to Buy and Sell Stock with Cooldown | best-time-to-buy-and-sell-stock-with-cooldown | M | dp-1d",
      "Best Time to Buy and Sell Stock III | best-time-to-buy-and-sell-stock-iii | H | dp-1d",
      "Distinct Subsequences | distinct-subsequences | H | dp-strings",
      "Russian Doll Envelopes | russian-doll-envelopes | H | dp-1d, binary-search",
      "Burst Balloons | burst-balloons | H | dp-interval",
      "Regular Expression Matching | regular-expression-matching | H | dp-strings",
      "Wildcard Matching | wildcard-matching | H | dp-strings, greedy",
    ] },
    { id: "bit-manipulation", name: "Bit Manipulation", questions: [
      "Single Number | single-number | E | bit-manipulation",
      "Number of 1 Bits | number-of-1-bits | E | bit-manipulation",
      "Counting Bits | counting-bits | E | bit-manipulation, dp-1d",
      "Reverse Bits | reverse-bits | E | bit-manipulation",
      "Missing Number | missing-number | E | bit-manipulation, cyclic-sort",
      "Power of Two | power-of-two | E | bit-manipulation",
      "Single Number II | single-number-ii | M | bit-manipulation",
      "Single Number III | single-number-iii | M | bit-manipulation",
      "Sum of Two Integers | sum-of-two-integers | M | bit-manipulation",
      "Bitwise AND of Numbers Range | bitwise-and-of-numbers-range | M | bit-manipulation",
      "Reverse Integer | reverse-integer | M | math",
    ] },
    { id: "math", name: "Math", questions: [
      "Palindrome Number | palindrome-number | E | math",
      "Plus One | plus-one | E | math",
      "Happy Number | happy-number | E | math, fast-slow",
      "Excel Sheet Column Title | excel-sheet-column-title | E | math",
      "Greatest Common Divisor of Strings | greatest-common-divisor-of-strings | E | math, string",
      "Pow(x, n) | powx-n | M | math",
      "Multiply Strings | multiply-strings | M | math, string",
      "Count Primes | count-primes | M | math",
    ] },
  ],
};
